require("nathan-wien.core.loadfirst")
require("nathan-wien.core.editor")
require("nathan-wien.plugins")
require("nathan-wien.core.loader")
require("nathan-wien.core.keymap")
require("nathan-wien.core.autocmd")
require("nathan-wien.core.globals")
