-- To view all available actions, do
-- Ctrl+Shift+P into 'Preferences: Open Default Keyboard Shortcuts'
local keys = require("nathan-wien.keys")
local vscode = require("vscode-neovim")

vim.keymap.set("n", keys.find.files, function()
  vscode.call("workbench.action.quickOpen")
end)
vim.keymap.set("n", keys.find.git_grep, function()
  vscode.call("workbench.action.findInFiles")
end)
vim.keymap.set("n", keys.find.commands, function()
  vscode.call("workbench.action.showCommands")
end)

vim.keymap.set("n", keys.lsp.code_actions, function()
  vscode.call("editor.action.codeAction")
end)
vim.keymap.set("n", keys.lsp.definition, function()
  vscode.call("editor.action.revealDefinition")
end)
vim.keymap.set("n", keys.lsp.declaration, function()
  vscode.call("editor.action.goToDeclaration")
end)
vim.keymap.set("n", keys.lsp.implementation, function()
  vscode.call("editor.action.goToImplementation")
end)
vim.keymap.set("n", keys.lsp.hover, function()
  vscode.call("editor.action.showHover")
end)
vim.keymap.set("n", keys.lsp.rename, function()
  vscode.call("editor.action.rename")
end)
vim.keymap.set("n", keys.lsp.type_definition, function()
  vscode.call("editor.action.goToTypeDefinition")
end)
vim.keymap.set("n", keys.lsp.usages, function()
  vscode.call("editor.action.goToReferences")
end)

vim.keymap.set("n", keys.git.hunk.next, function()
  vscode.call("workbench.action.editor.nextChange")
end)
vim.keymap.set("n", keys.git.hunk.prev, function()
  vscode.call("workbench.action.editor.previousChange")
end)

vim.keymap.set("n", keys.view.filetree, function()
  -- vscode.call("workbench.view.explorer")
  vscode.call("workbench.action.toggleSidebarVisibility")
end)
