" Custom conceal
" https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode
" https://github.com/lervag/vimtex/blob/master/autoload/vimtex/syntax/core.vim

let s:cmd_symbols = [
      \ ['bigsqcap', '⊓'],
      \]

function! s:match_math_symbols() abort " {{{1
  if !g:vimtex_syntax_conceal.math_symbols | return | endif

  for [l:cmd, l:symbol] in s:cmd_symbols
    execute 'syntax match texMathSymbol'
          \ '"\\' . l:cmd . '\ze\%(\>\|[_^]\)"'
          \ 'contained conceal cchar=' . l:symbol
  endfor
endfunction

call s:match_math_symbols()

" let s:cmd_symbols = [
"       \ ['aleph', 'ℵ'],
"       \ ['amalg', '∐'],
"       \ ['angle', '∠'],
"       \ ['approx', '≈'],
"       \ ['ast', '∗'],
"       \ ['asymp', '≍'],
"       \ ['backslash', '∖'],
"       \ ['bigcap', '∩'],
"       \ ['bigcirc', '○'],
"       \ ['bigcup', '∪'],
"       \ ['bigodot', '⊙'],
"       \ ['bigoplus', '⊕'],
"       \ ['bigotimes', '⊗'],
"       \ ['bigsqcap', '⊓'],
"       \ ['bigsqcup', '⊔'],
"       \ ['bigtriangledown', '∇'],
"       \ ['bigtriangleup', '∆'],
"       \ ['bigvee', '⋁'],
"       \ ['bigwedge', '⋀'],
"       \ ['bot', '⊥'],
"       \ ['bowtie', '⋈'],
"       \ ['bullet', '•'],
"       \ ['cap', '∩'],
"       \ ['cdot', '·'],
"       \ ['cdots', '⋯'],
"       \ ['circ', '∘'],
"       \ ['clubsuit', '♣'],
"       \ ['cong', '≅'],
"       \ ['coprod', '∐'],
"       \ ['copyright', '©'],
"       \ ['cup', '∪'],
"       \ ['dagger', '†'],
"       \ ['dashv', '⊣'],
"       \ ['ddagger', '‡'],
"       \ ['ddots', '⋱'],
"       \ ['diamond', '⋄'],
"       \ ['diamondsuit', '♢'],
"       \ ['div', '÷'],
"       \ ['doteq', '≐'],
"       \ ['dots', '…'],
"       \ ['downarrow', '↓'],
"       \ ['Downarrow', '⇓'],
"       \ ['ell', 'ℓ'],
"       \ ['emptyset', 'Ø'],
"       \ ['equiv', '≡'],
"       \ ['exists', '∃'],
"       \ ['flat', '♭'],
"       \ ['forall', '∀'],
"       \ ['frown', '⁔'],
"       \ ['ge', '≥'],
"       \ ['geq', '≥'],
"       \ ['gets', '←'],
"       \ ['gg', '⟫'],
"       \ ['hbar', 'ℏ'],
"       \ ['heartsuit', '♡'],
"       \ ['hookleftarrow', '↩'],
"       \ ['hookrightarrow', '↪'],
"       \ ['iff', '⇔'],
"       \ ['Im', 'ℑ'],
"       \ ['imath', 'ɩ'],
"       \ ['in', '∈'],
"       \ ['infty', '∞'],
"       \ ['int', '∫'],
"       \ ['iint', '∬'],
"       \ ['iiint', '∭'],
"       \ ['jmath', '𝚥'],
"       \ ['land', '∧'],
"       \ ['lnot', '¬'],
"       \ ['lceil', '⌈'],
"       \ ['ldots', '…'],
"       \ ['le', '≤'],
"       \ ['leftarrow', '←'],
"       \ ['Leftarrow', '⇐'],
"       \ ['leftharpoondown', '↽'],
"       \ ['leftharpoonup', '↼'],
"       \ ['leftrightarrow', '↔'],
"       \ ['Leftrightarrow', '⇔'],
"       \ ['lhd', '◁'],
"       \ ['rhd', '▷'],
"       \ ['leq', '≤'],
"       \ ['ll', '≪'],
"       \ ['lmoustache', '╭'],
"       \ ['lor', '∨'],
"       \ ['mapsto', '↦'],
"       \ ['mid', '∣'],
"       \ ['models', '⊨'],
"       \ ['mp', '∓'],
"       \ ['nabla', '∇'],
"       \ ['natural', '♮'],
"       \ ['ne', '≠'],
"       \ ['nearrow', '↗'],
"       \ ['neg', '¬'],
"       \ ['neq', '≠'],
"       \ ['ni', '∋'],
"       \ ['notin', '∉'],
"       \ ['nwarrow', '↖'],
"       \ ['odot', '⊙'],
"       \ ['oint', '∮'],
"       \ ['ominus', '⊖'],
"       \ ['oplus', '⊕'],
"       \ ['oslash', '⊘'],
"       \ ['otimes', '⊗'],
"       \ ['owns', '∋'],
"       \ ['P', '¶'],
"       \ ['parallel', '║'],
"       \ ['partial', '∂'],
"       \ ['perp', '⊥'],
"       \ ['pm', '±'],
"       \ ['prec', '≺'],
"       \ ['preceq', '⪯'],
"       \ ['prime', '′'],
"       \ ['prod', '∏'],
"       \ ['propto', '∝'],
"       \ ['rceil', '⌉'],
"       \ ['Re', 'ℜ'],
"       \ ['quad', ' '],
"       \ ['qquad', ' '],
"       \ ['rightarrow', '→'],
"       \ ['Rightarrow', '⇒'],
"       \ ['leftarrow', '←'],
"       \ ['Leftarrow', '⇐'],
"       \ ['rightleftharpoons', '⇌'],
"       \ ['rmoustache', '╮'],
"       \ ['S', '§'],
"       \ ['searrow', '↘'],
"       \ ['setminus', '⧵'],
"       \ ['sharp', '♯'],
"       \ ['sim', '∼'],
"       \ ['simeq', '⋍'],
"       \ ['smile', '‿'],
"       \ ['spadesuit', '♠'],
"       \ ['sqcap', '⊓'],
"       \ ['sqcup', '⊔'],
"       \ ['sqsubset', '⊏'],
"       \ ['sqsubseteq', '⊑'],
"       \ ['sqsupset', '⊐'],
"       \ ['sqsupseteq', '⊒'],
"       \ ['star', '✫'],
"       \ ['subset', '⊂'],
"       \ ['subseteq', '⊆'],
"       \ ['succ', '≻'],
"       \ ['succeq', '⪰'],
"       \ ['sum', '∑'],
"       \ ['supset', '⊃'],
"       \ ['supseteq', '⊇'],
"       \ ['surd', '√'],
"       \ ['swarrow', '↙'],
"       \ ['times', '×'],
"       \ ['to', '→'],
"       \ ['top', '⊤'],
"       \ ['triangle', '∆'],
"       \ ['triangleleft', '⊲'],
"       \ ['triangleright', '⊳'],
"       \ ['uparrow', '↑'],
"       \ ['Uparrow', '⇑'],
"       \ ['updownarrow', '↕'],
"       \ ['Updownarrow', '⇕'],
"       \ ['vdash', '⊢'],
"       \ ['vdots', '⋮'],
"       \ ['vee', '∨'],
"       \ ['wedge', '∧'],
"       \ ['wp', '℘'],
"       \ ['wr', '≀'],
"       \ ['implies', '⇒'],
"       \ ['choose', 'C'],
"       \ ['sqrt', '√'],
"       \ ['colon', ':'],
"       \ ['coloneqq', '≔'],
"       \]

