---
- hosts: localhost
  vars:
    nvim_stdpath_data: "{{ ansible_env.HOME }}/.local/share/nvim"
  tasks:
    - name: pip - install pip dependencies
      import_tasks: tasks/pip.yml
      tags:
        - pip
