- name: java-debug | download
  ansible.builtin.git:
    repo: "https://github.com/microsoft/java-debug"
    version: 0.39.0
    dest: "{{ nvim_stdpath_data }}/jdtls/plugins/java-debug"

- name: java-debug | install
  shell:
    chdir: "{{ nvim_stdpath_data }}/jdtls/plugins/java-debug"
    cmd: ./mvnw clean install

- name: vscode-java-test | download
  ansible.builtin.git:
    repo: "https://github.com/microsoft/vscode-java-test"
    version: 0.36.0
    dest: "{{ nvim_stdpath_data }}/jdtls/plugins/vscode-java-test"
  tags:
    - java-test

- name: vscode-java-test | npm install
  npm:
    path: "{{ nvim_stdpath_data }}/jdtls/plugins/vscode-java-test"
  tags:
    - java-test

- name: java-debug | build
  shell:
    chdir: "{{ nvim_stdpath_data }}/jdtls/plugins/vscode-java-test"
    cmd: npm run build-plugin
  tags:
    - java-test
